#spring:
#  datasource:
#    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/lanchonete}
#    username: username
#    password: password
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        globally_quoted_identifiers: false
#        globally_quoted_identifiers_skip_column_definitions: true
#        batch_fetch_style: dynamic
#        default_batch_fetch_size: 16
#        jdbc:
#          batch_size: 16
#          order_inserts: true
#          order_updates: true
#    show-sql: true
#    generate-ddl: true

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb/lanchonete
    username: username
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    database: H2

server:
  servlet:
    context-path: /lanchonete-cliente/api/v1
  port: 8080
  host: http://localhost


#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE

mercado-pago:
  enabled: ${MERCADO_PAGO_ENABLED:false}
  bearer-token: TEST-??????????-??????????-??????????
  collector-id: ??????????
  pos-id: SUC001POSSUC001001